---
output: stevetemplates::cv
geometry: margin=0.5in

title: "CV"
author: Rocco Zizzamia

#jobtitle: ""
address: "Centre for the Study of African Economies · Manor Rd · Oxford OX1 3UQ, UK"
fontawesome: yes
email: rocco.zizzamia@economics.ox.ac.uk
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
#phone: "+44 744 969 5005"
web: roccozizzamia.github.io
#updated: TRUE
#rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 9.5pt
linkcolor: blue
urlcolor: blue
---

# Current appointments

Fulford Junior Research Fellow (Somerville College, Oxford University) \hfill Oct. 2023-present

Post-doctoral researcher in Economics (University of Oxford) \hfill Nov. 2022-present
# Education

*University of Oxford*, DPhil, International Development \hfill 2023

*University of Oxford*, MPhil, Development Studies, concentration in Dev. Econ. (Distinction)  \hfill 2018

*University of Cape Town*, Bachelor of Arts (Honours) in Economic History (First Class)  \hfill 2015

*University of Cape Town*, Bachelor of Social Science in Philosophy (First Class)  \hfill 2014

# Research

## Selected publications
Jain, R., Budlender, J., Zizzamia, R., & Bassier, I. (2023). [The labor market and poverty impacts of COVID-19 in South Africa](https://doi.org/10.1111/saje.12356). *South African Journal of Economics.* 91(4), 419-445.

Schotte, S., & Zizzamia, R. (2022). [The livelihood impacts of COVID-19 in urban South Africa: A view from below](https://link.springer.com/article/10.1007/s11205-022-02978-7). *Social Indicators Research*. 1-30.

Zizzamia, R., Schotte, S., & Leibbrandt, M. (2022). ([Snakes and Ladders and Loaded Dice: Poverty Dynamics and Inequality in South Africa](https://onlinelibrary.wiley.com/doi/full/10.1111/saje.12308), 2008 to 2017. *South African Journal of Economics.* 214-242.

Zizzamia, R., Bassier, I., Budlender, J., Leibbrandt, M., & Ranchhod, V. (2021). [Locked down and locked out: Repurposing social assistance as emergency relief to informal workers.](https://doi.org/10.1016/j.worlddev.2020.105271) *World Development*, 139, 105271.

Clementi, F., Fabiani, M., Molini, V., & Zizzamia, R. (2021). [Are We Really Painting the Devil on the Walls? Polarization and its Drivers in Sub-Saharan Africa in the Past Two Decades.](https://doi.org/10.1093/jae/ejab006) *Journal of African Economies.*

Zizzamia, R. (2020). [Is employment a panacea for poverty: A mixed-methods investigation into employment decisions in South Africa.](https://doi.org/10.1016/j.worlddev.2020.104938) *World Development.* 130. 104938.

<!-- Leibbrandt, M., Schotte, S., & **Zizzamia, R.** (2019). Tackling persistent poverty and inequality: A dynamic perspective. In *Confronting Inequality: The South African Crisis*, edited by M.S. Smith. Jacana Media. -->

Schotte, S., Zizzamia, R., & Leibbrandt, M. (2018). [A poverty dynamics approach to social stratification: The South African case.](https://doi.org/10.1016/j.worlddev.2018.05.024) *World Development*, 110, 88-103.


## Selected work in progress

[Acting early under uncertainty: Anticipatory cash transfers in the context of flood disasters](https://www.povertyactionlab.org/initiative-project/improved-early-action-through-precise-targeting-timely-cash-and-early-warning) (with Stefan Dercon, Ashley Pople, Hannah Timmis, Prabhmeet Matta, BIGD Dhaka) 

Rejection sensitivity and on-the-job search: A lab-in-the-field experiment in South Africa. **Revise and Resubmit*, *Journal of Behavioural and Experimental Economics**

Optimal household targeting of cash transfers in a shock setting (with Hannah Timmis, Stefan Dercon, Ashley Pople, Prabhmeet Matta, BIGD Dhaka) 

Group Coaching and the Scalability of Ultra-Poor Graduation Programs: Evidence from Three Field Experiments (with Stefan Dercon, Emily Beam, Dean Karlan, and others)

Welfare-Risk Trade-offs in Anticipatory Aid: A Portfolio Theory Approach (with Prabhmeet Matta)

# Research and Teaching Experience

## Research 
Consultant (International Labour Organization) \hfill 2022

Research Officer (Southern African Labour and Develompemnt Research Unit)  \hfill 2016 - 2021

Consultant (National Income Dynamics Study-Coronavirus Rapid Mobile Survey) \hfill 2020

Visiting Fellow (GIGA German Institute for Global and Area Studies) \hfill 2018

Short-Term Consultant (World Bank Group, Poverty Global Practice Unit) \hfill 2017 - 2018

## Teaching 

Lecturer, Quantitative Methods (Oxford Dept. of International Development) \hfill 2024-2025

TA, Quantitative Methods (Oxford Dept. of International Development) \hfill 2020-2022

TA, Various (Philosophy Dept., University of Cape Town) \hfill 2013 - 2014

# Grants (PI or co-PI)

*Anticipatory action for climate disaster response*, Weiss Asset Management Foundation (**$1,000,000**)  \hfill  2024 - 2025

*Anticipatory action for climate disaster response*, J-Pal King Climate Action Initiative (**$250,000**) \hfill  2023 - 2025

*Boosting decent employment for Africa’s youth*, International Development Research Centre (**CAD$500,000**)  \hfill  2019 - 2022

*Working to learn: an evaluation of on-the-job training*, J-Pal Post-Primary Education Initiative (**$25,000**)  \hfill  2019 - 2022

<!-- *COVID-19 and livelihoods in urban South Africa*, UNU-WIDER\ -->
<!-- **$8,000**  \hfill  2020 - 2021 -->

<!-- *Poverty dynamics in South Africa: A mixed methods investigation*, German Institute for Global and Area Studies\ -->
<!-- **$8,000**  \hfill  2017 -->


# Awards

Papiya Ghosh Thesis Prize (best MPhil thesis) (2018); Clarendon Scholarship (2019 - 2022); Oxford Dept. International Development Scholarship (2022 - 2023); Skye Foundation Scholarship (2016 - 2018); Michael Wills Scholarship (2016 - 2018)


# Presentations 

Since 2016 I have presented original research at over 30 international conferences and seminars. 

<!-- **2024** — a2i x GiveDirectly Conference, Dhaka (online); NOVAFRICA Conference on Economic Development, Lisbon; Oxford Economics Department Jamboree, Oxford -->

<!-- **2023** — Department of Social Policy and Intervention workshop, Oxford; CREB Applied Development Economics, Lahore; ESA Africa Regional Conference, Cape Town; Path2Dev Conference, LUMS, Lahore -->

<!-- **2022** — WB/IZA/UNU-WIDER Conference, Cape Town; CSAE Workshop, Oxford -->

<!-- **2021** — UNU-WIDER Seminar, Helsinki (online); RESEP Seminar, Stellenbosch; CSAE Workshop, Oxford -->

<!-- **2020** — Agence Française de Développement; SALDRU; African Centre for Excellence in Inequality Research; IUSSP Population, Poverty and Inequality Research Conference (all online) -->

<!-- **2019** — IDRC/ILO/INCLUDE Workshop, Nairobi; WB/IZA/UNU-WIDER Conference, Bangkok; IUSSP Conference, University of Michigan -->

<!-- **2018** — CSAE Conference, Oxford; SALDRU Seminar, Cape Town; RESEP Seminar, Stellenbosch; African Studies Centre, Oxford; INET-YSI Africa, Harare; HDCA Conference, Buenos Aires; AFD Conference, Paris; GIGA Seminar, Hamburg -->

<!-- **2017** — Fifth Congress of African Economists, Malabo; HDCA Conference, Cape Town; CSAE Conference, Oxford; African Studies Centre, Oxford -->

<!-- **2016** — DSA Conference, Oxford; SALDRU Seminar, Cape Town; International Workshop on the Middle Class in Africa, Cape Town -->


# Public engagement
My research has been featured in the [Financial Times](https://www.ft.com/content/85ad034e-146d-4e8f-a3ad-f8d237346d6d), The Economist ([1](https://www.economist.com/middle-east-and-africa/2020/07/18/covid-19-has-throttled-south-africas-economy), [2](https://www.economist.com/middle-east-and-africa/2024/05/02/how-south-africa-has-changed-30-years-after-apartheid), [3](https://www.economist.com/special-report/2019/04/25/cyril-ramaphosa-faces-a-daunting-task-if-he-wins-south-africas-election), [4](https://www.economist.com/middle-east-and-africa/2021/01/07/south-africas-black-middle-class-has-prospered-under-democracy)), [The Mail and Guardian](https://mg.co.za/news/2020-07-15-three-million-jobs-lost-and-hunger-surging-amid-covid-19-crisis-survey/), among others. My own public-facing writing can be found [here](https://roccozizzamia.github.io/otherwriting/).

# Service

**Policy engagement**: Policy modeling for the [Special Covid Grant Working group](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://covid19economicideas.org/wp-content/uploads/2020/04/Special-Covid-19-Grant-Proposal-full-version-17-April-2020.pdf) -- our proposal to introduce a [Social Relief of Distress Grant](https://www.gov.za/services/services-residents/social-benefits/social-relief-distress#:~:text=Social%20relief%20of%20distress%20is,children's%20grants%20to%20be%20processed) was adopted by the South African government.

**Mentoring:** Co-founder of the [Oxford Africa Society Mentorship Scheme](https://www.oxforduniversityafricasociety.com/scholarship-access-mentorship)

**Refereeing**: Journal of Economic Inequality; Economic Modelling; World Development; Review of Development Economics; Applied Economics Letters; South African Journal of Economics.

**Editor:** [CSAE Working Paper Series](https://www.csae.ox.ac.uk/working-papers?filter_types-3013581[]=c-report&filter_series-3013581[]=1356606,2072376,1429171)

**Organiser:** CSAE Workshop on Social Protection and Climate Adaptation (2024); CSAE Research Seminar Series (2024-2025)
<!-- ## Organization -->

<!-- ## Refereeing -->

<!-- ## Mentoring -->

# Other information
**Software** - Python, Stata, R ; **Languages** - English, Italian
